# This is just a constant which preloads all card images which are used in the game
# This is to avoid loading files during runtime and to be able to easier map filenames
# to card names.
class_name ImageLibrary
extends Reference

const FINAL_IMAGES := {
	"The Whippy-Flippy": "res://assets/cards/The Whippy-Flippy.jpg",
	"Nunclucks": "res://assets/cards/Nunclucks.jpg",
	"Keep in Mind": "res://assets/cards/Keep in Mind.jpg",
	"Pialephant": "res://assets/cards/pialephant.jpg",
	"Broken Mirror": "res://assets/cards/broken_mirror.jpg",
	"The Light Calling": "res://assets/cards/The Light Calling.jpg",
	"A Squirrel": "res://assets/cards/Squirrel.jpg",
}
const BETA_IMAGES := {
	"Catatonia": "res://assets/cards/Catatonia.jpg",
	"Could Be Worse": "res://assets/cards/Could Be Worse.jpg",
	"Dismissal": "res://assets/cards/Dismissal.jpg",
	"Eureka!": "res://assets/cards/Eureka!.jpg",
	"Hyperfocus": "res://assets/cards/Hyperfocus.jpg",
	"Inner Justice": "res://assets/cards/Inner Justice.jpg",
	"Interpretation": "res://assets/cards/Interpretation.jpg",
	"Is it my fault?": "res://assets/cards/Is It My Fault.jpg",
	"Lash-out": "res://assets/cards/Lash-Out.jpg",
	"Prejudice": "res://assets/cards/Prejudice.jpg",
	"Rancor": "res://assets/cards/Rancor.jpg",
	"Rapid Theorizing": "res://assets/cards/Rapid Theorizing.jpg",
	"Self-Deception": "res://assets/cards/Self-Deception.jpg",
	"The Happy Place": "res://assets/cards/The Happy Place.jpg",
	"Tolerance": "res://assets/cards/Tolerance.jpg",
	"Introspection": "res://assets/cards/Introspection.jpg",
	"Change of Mind": "res://assets/cards/Change of Mind.jpg",
	"Misunderstood": "res://assets/cards/Misunderstood.jpg",
	"Mania": "res://assets/cards/Mania.jpg",
	"Terror": "res://assets/cards/beta_eyeball.jpg",
	"Discombobulation": "res://assets/cards/beta_hands.jpg",
	"The Laughing One": "res://assets/cards/beta_smiler.jpg",
	"Confidence": "res://assets/cards/confidence.jpg",
	"Lacuna": "res://assets/cards/doodle2.jpg",
	"Unease": "res://assets/cards/doodle1.jpg",
	"Dread": "res://assets/cards/doodle3.jpg",
	"Impossible Construction": "res://assets/cards/Impossible_Construction.jpg",
	"Excogitate": "res://assets/cards/excogitate.jpg",
	"Dive-in": "res://assets/cards/Dive-in.jpg",
	"Safety of Air": "res://assets/cards/Safety of Air.jpg",
	"Nothing to Fear": "res://assets/cards/Nothing to Fear.jpg",
	"Out of Reach": "res://assets/cards/Out of Reach.jpg",
	"Confounding Movements": "res://assets/cards/Confounding Movements.jpg",
	"Noisy Whip": "res://assets/cards/Noisy Whip.jpg",
	"Whirlwind": "res://assets/cards/whirlwind.jpg",
	"Overview": "res://assets/cards/overview.jpg",
	"Rubber Eggs": "res://assets/cards/Rubber Eggs.jpg",
	"Towering Presence": "res://assets/cards/Towering Presence.jpg",
	"The Joke": "res://assets/cards/The Joke.jpg",
	"Confident Slap": "res://assets/cards/Confident Slap.jpg",
	
	# Reusing Journal Art. SHould eventually get proper illustrations
	"Stuffed Toy": "res://assets/journal/torments/stuffed_toy.jpeg",
	"Hyena": "res://assets/journal/torments/hyena.jpeg",
	"Baby": "res://assets/journal/torments/baby.jpeg",
	"Traffic Jam": "res://assets/journal/torments/traffic_jam.jpeg",
	"Gaslighter": "res://assets/journal/torments/gaslighter2.png",
	"Butterfly": "res://assets/journal/torments/butterfly.jpeg",
	"Clown": "res://assets/journal/torments/clown.jpeg",
	"Fearmonger": "res://assets/journal/torments/fearmonger.jpeg",
	"Mouse": "res://assets/journal/torments/mouse.jpeg",
	"Murmurs": "res://assets/journal/torments/murmurs.jpeg",
	"The Critic": "res://assets/enemies/the_critic.png",
	"The Victim": "res://assets/journal/torments/the_victim.jpeg",
	"The Exam": "res://assets/journal/torments/exam.jpeg",
	"Void": "res://assets/journal/torments/void.jpeg",
	"Cringelord": "res://assets/journal/torments/cringelord.jpeg",
	"Life Path": "res://assets/journal/torments/life_path.jpeg",
	"Silent Treatment": "res://assets/journal/torments/silent_treatment.jpeg",
	"Chasm": "res://assets/journal/nce/chasm.jpeg",
	"Guilt": "res://assets/journal/torments/guilt.jpeg",
	"Nightmare": "res://assets/journal/torments/nightmare.jpeg",
	"Submerged": "res://assets/journal/torments/submerged.jpg",
	"Cockroach Infestation": "res://assets/journal/nce/cockroach.jpeg",
	"Cockroaches": "res://assets/journal/nce/cockroach.jpeg",
	"Handsy Aunt": "res://assets/journal/torments/handsy_aunt.jpeg",
	"Influencer": "res://assets/journal/torments/influencer.jpg",
	"Shameling": "res://assets/journal/torments/shameling.jpg",
	"Administration": "res://assets/journal/torments/administration.jpg",
}
