# This is just a constant which preloads all card images which are used in the game
# This is to avoid loading files during runtime and to be able to easier map filenames
# to card names.
class_name ImageLibrary
extends Reference

const CARD_IMAGES := {
	"Catatonia": preload("res://assets/cards/Catatonia.jpg"),
	"Could Be Worse": preload("res://assets/cards/Could Be Worse.jpg"),
	"Dismissal": preload("res://assets/cards/Dismissal.jpg"),
	"Eureka!": preload("res://assets/cards/Eureka!.jpg"),
	"Hyperfocus": preload("res://assets/cards/Hyperfocus.jpg"),
	"Inner Justice": preload("res://assets/cards/Inner Justice.jpg"),
	"Interpretation": preload("res://assets/cards/Interpretation.jpg"),
	"Is it my fault?": preload("res://assets/cards/Is It My Fault.jpg"),
	"Lash-out": preload("res://assets/cards/Lash-Out.jpg"),
	"Prejudice": preload("res://assets/cards/Prejudice.jpg"),
	"Rancor": preload("res://assets/cards/Rancor.jpg"),
	"Rapid Theorizing": preload("res://assets/cards/Rapid Theorizing.jpg"),
	"Self-Deception": preload("res://assets/cards/Self-Deception.jpg"),
	"The Happy Place": preload("res://assets/cards/The Happy Place.jpg"),
	"Tolerance": preload("res://assets/cards/Tolerance.jpg"),
	"Introspection": preload("res://assets/cards/Introspection.jpg"),
	"Change of Mind": preload("res://assets/cards/Change of Mind.jpg"),
	"Misunderstood": preload("res://assets/cards/Misunderstood.jpg"),
	"Mania": preload("res://assets/cards/Mania.jpg"),
	"The Whippy-Flippy": preload("res://assets/cards/The Whippy-Flippy.jpg"),
	"Terror": preload("res://assets/cards/beta_eyeball.jpg"),
	"Discombobulation": preload("res://assets/cards/beta_hands.jpg"),
	"The Laughing One": preload("res://assets/cards/beta_smiler.jpg"),
	"Broken Mirror": preload("res://assets/cards/broken_mirror.jpg"),
	"Pialephant": preload("res://assets/cards/pialephant.jpg"),
	"The Light Calling": preload("res://assets/cards/The Light Calling.jpg"),
	"A Squirrel": preload("res://assets/cards/Squirrel.jpg"),
	"Confidence": preload("res://assets/cards/confidence.jpg"),
	"Lacuna": preload("res://assets/cards/doodle2.jpg"),
	"Unease": preload("res://assets/cards/doodle1.jpg"),
	"Dread": preload("res://assets/cards/doodle3.jpg"),
	"Impossible Construction": preload("res://assets/cards/Impossible_Construction.jpg"),
	"Excogitate": preload("res://assets/cards/excogitate.jpg"),
	
	# Reusing Journal Art. SHould eventually get proper illustrations
	"Stuffed Toy": preload("res://assets/journal/torments/stuffed_toy.jpeg"),
	"Hyena": preload("res://assets/journal/torments/hyena.jpeg"),
	"Baby": preload("res://assets/journal/torments/baby.jpeg"),
	"Traffic Jam": preload("res://assets/journal/torments/traffic_jam.jpeg"),
	"Gaslighter": preload("res://assets/journal/torments/gaslighter.jpeg"),
	"Butterfly": preload("res://assets/journal/torments/butterfly.jpeg"),
	"Clown": preload("res://assets/journal/torments/clown.jpeg"),
	"Fearmonger": preload("res://assets/journal/torments/fearmonger.jpeg"),
	"Mouse": preload("res://assets/journal/torments/mouse.jpeg"),
	"Murmurs": preload("res://assets/journal/torments/murmurs.jpeg"),
	"The Critic": preload("res://assets/journal/torments/the_critic.jpeg"),
	"The Victim": preload("res://assets/journal/torments/the_victim.jpeg"),
	"The Exam": preload("res://assets/journal/torments/exam.jpeg"),
	"Void": preload("res://assets/journal/torments/void.jpeg"),
	"Cringelord": preload("res://assets/journal/torments/cringelord.jpeg"),
	"Life Path": preload("res://assets/journal/torments/life_path.jpeg"),
	"Silent Treatment": preload("res://assets/journal/torments/silent_treatment.jpeg"),
	"Chasm": preload("res://assets/journal/nce/chasm.jpeg"),
	"Guilt": preload("res://assets/journal/torments/guilt.jpeg"),
	"Nightmare": preload("res://assets/journal/torments/nightmare.jpeg"),
}
