class_name CoreDefinitions
extends Reference

const SET = "Core Set"
const CARDS := {
	"Confidence": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Gain 5 confidence.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Assault": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Interpret target Torment for 6.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Untouchable": {
		"Type": "Control",
		"Tags": ["Untouchable"],
		"Abilities": "Gain 1 Untouchable.",
		"Cost": 3,
		"_illustration": "Nobody",
	},
	"Dive-in": {
		"Type": "Control",
		"Tags": ["Risky"],
		"Abilities": "Gain 2 Shaken. Your next interpretation is doubled.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Safety of Air": {
		"Type": "Control",
		"Tags": ["Calm"],
		"Abilities": "Relax for 4. Forget",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Nothing to Fear": {
		"Type": "Concentration",
		"Tags": ["Purpose"],
		"Abilities": "Gain 1 Immersion at the start of each turn."\
			+ " Increase all anxiety taken from Torment intents by 2.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Confounding Movements": {
		"Type": "Control",
		"Tags": ["Confusing"],
		"Abilities": "Gain 4 confidence. Apply 1 Confusion to target Torment.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Noisy Whip": {
		"Type": "Action",
		"Tags": ["Confusing"],
		"Abilities": "Interpret target Torment for 5 and apply Confusion.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Inner Justice": {
		"Type": "Control",
		"Tags": ["Purpose"],
		"Abilities": "Gain 5 Immersion",
		"Cost": 3,
		"_illustration": "Nobody",
	},
	"Whirlwind": {
		"Type": "Action",
		"Tags": ["Chain"],
		"Abilities": "Interpret target Torment for 3. Repeat 3 times",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Overview": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Remove all Perplexity from target Torment.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"War Paint": { #TODO
		"Type": "Control",
		"Tags": [],
		"Abilities": "All interpretation is increased by 1 this turn.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Rubber Eggs": {
		"Type": "Concentration",
		"Tags": [],
		"Abilities": "At the start of your turn, interpret a random Confused Torment for 6.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"The Joke": {
		"Type": "Action",
		"Tags": ["Confusing"],
		"Abilities": "Target a Torment. If it's not confused. Apply 3 Confusion."\
			+ " If it is confused, interpret it for 10.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Nunclucks": {
		"Type": "Concentration",
		"Tags": [],
		"Abilities": "Increase your interpretation by 1, for each stack of Confusion on the Torment.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Gummiraptor": {
		"Type": "Action",
		"Tags": ["Chain"],
		"Abilities": "Interpret Torment for 10."\
			+ "Repeat this if Torments are not going to be inflicting any anxiety this turn.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Cocky Retort": {
		"Type": "Control",
		"Tags": ["Swift"],
		"Abilities": "Gain 8 confidence. Draw a card.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Rapid Encriclement": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Apply 2 Shaken to all Torments.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Barrel Through": {
		"Type": "Action",
		"Tags": ["Risky", "Chain"],
		"Abilities": "Interpret a Torment for 8. If the Torment is Shaken, interpet all other Torments for 12.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Intimidate": {
		"Type": "Control",
		"Tags": ["Doubt"],
		"Abilities": "Apply 2 Doubt to all Torments",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Cheeky Approach": {
		"Type": "Control",
		"Tags": ["Doubt"],
		"Abilities": "Gain 10 Confidence, Apply 3 Doubt to target Torment.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Laugh at Danger": {
		"Type": "Concentration",
		"Tags": ["Doubt"],
		"Abilities": "After a Torment inflicts anxiety, it gains 1 Doubt.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Towering Presence": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Interpret a Torment equal to your current Confidence",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Unassailable": {
		"Type": "Concentration",
		"Tags": [],
		"Abilities": "Whenever you apply Doubt, gain 1 Confidence.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Courage": {
		"Type": "Control",
		"Tags": ["Courage"],
		"Abilities": "Gain 8 Confidence. Apply 1 Courage.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Boast": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Double your Confidence. Remove all Courage. Forget.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Solid Understanding": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Gain 5 Confidence. Interpret Torment for 5.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"No Second Thoughts": {
		"Type": "Control",
		"Tags": ["Courage"],
		"Abilities": "Gain 2 Courage",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"High Morale": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Interpret Torment for 6. Draw a Courage card.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Confident Slap": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Apply 5 Doubt to target Torment.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Swoop": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Interpret for 7. If Untouchable, interpret for 12 instead.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Drag and Drop": {
		"Type": "Action",
		"Tags": ["Untouchable"],
		"Abilities": "Interpret Torment for 10. If Torment is Overcome, gain 1 Untouchable.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Running Start": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Interpret for 5. Draw 1 Untouchable card.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Master of Skies": {
		"Type": "Concentration",
		"Tags": ["Purpose"],
		"Abilities": "Whenever you gain Untouchable. Gain 1 Immersion.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Zen of Flight": {
		"Type": "Concentration",
		"Tags": ["Calm"],
		"Abilities": "At the end of each turn, lose 1 Anxiety. If Untouchable, lose 1 extra Anxiety.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Loop de loop": {
		"Type": "Control",
		"Tags": ["Purpose"],
		"Abilities": "Gain 7 Confidence. Next Turn gain 1 Immersion.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Headless": {
		"Type": "Control",
		"Tags": ["Purpose"],
		"Abilities": "Next turn, gain 4 Immersion.",
		"Cost": 2,
		"_illustration": "Nobody",
	},
	"Utterly Ridiculous": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "If there's a total of 6 Confusion or more among Torments, Interpret all Torments for 20",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"Ventriloquism": {
		"Type": "Action",
		"Tags": [],
		"Abilities": "Interpret a Torment for 8. Draw a Confusion card.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"unnamed_card_1": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Shuffle your discard pile into your deck. Play a Random card from your deck. Forget.",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"unnamed_card_2": {
		"Type": "Control",
		"Tags": ["Doubt"],
		"Abilities": "Each Torment is applied Doubt equals to its Confusion x2",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"unnamed_card_3": {
		"Type": "Control",
		"Tags": [],
		"Abilities": "Interpret all Torments for 8",
		"Cost": 1,
		"_illustration": "Nobody",
	},
	"unnamed_card_4": {
		"Type": "Concentration",
		"Tags": [],
		"Abilities": "Whenever you apply Confusion to a Torment, interpret it for 3",
		"Cost": 1,
		"_illustration": "Nobody",
	},
}
