name: GUT

on:
  push:
    branches-ignore:
      - main
      - steam_upload
      - gut

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GUT_Tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Unit & Integration Tests

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check out personal godot-tester repository
        uses: actions/checkout@v3
        # with:
        #   repository: db0/godot-tester
        #   path: ./.github/actions/godot-tester
      # Runs a single command using the runners shell
      - name: Godot Tester
        uses: croconut/godot-tester@v5.2
        with:
          version: 3.6
          # should be long enough for asset import files to get generated
          import-time: 5000
          assert-check: true
          max-fails: 0
          # How long the test should be run before it's timed out and fails
          test-timeout: 3600
          # Directory containing Gut tests
          direct-scene: tests/cli/tests.tscn
          custom-godot-dl-url: https://github.com/godotengine/godot/releases/download/3.6-stable/Godot_v3.6-stable_linux_headless.64.zip
          custom-godot-binary-path: "Godot_v3.6-stable_linux_headless.64"        

